\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename alexandria.info
@settitle Alexandria-2 Manual
@c %**end of header

@settitle Alexandria-2 Manual -- draft version

@c for install-info
@dircategory Software development
@direntry
* alexandria:           Common Lisp utilities.
@end direntry

@copying
Alexandria software and associated documentation are in the public
domain:

@quotation
  Authors dedicate this work to public domain, for the benefit of the
  public at large and to the detriment of the authors' heirs and
  successors. Authors intends this dedication to be an overt act of
  relinquishment in perpetuity of all present and future rights under
  copyright law, whether vested or contingent, in the work. Authors
  understands that such relinquishment of all rights includes the
  relinquishment of all rights to enforce (by lawsuit or otherwise)
  those copyrights in the work.

  Authors recognize that, once placed in the public domain, the work
  may be freely reproduced, distributed, transmitted, used, modified,
  built upon, or otherwise exploited by anyone for any purpose,
  commercial or non-commercial, and in any way, including by methods
  that have not yet been invented or conceived.
@end quotation

In those legislations where public domain dedications are not
recognized or possible, Alexandria is distributed under the following
terms and conditions:

@quotation
  Permission is hereby granted, free of charge, to any person
  obtaining a copy of this software and associated documentation files
  (the "Software"), to deal in the Software without restriction,
  including without limitation the rights to use, copy, modify, merge,
  publish, distribute, sublicense, and/or sell copies of the Software,
  and to permit persons to whom the Software is furnished to do so,
  subject to the following conditions:

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
@end quotation
@end copying

@titlepage

@title Alexandria-2 Manual
@subtitle draft version

@c The following two commands start the copyright page.
@page
@vskip 0pt plus 1filll
@insertcopying

@end titlepage

@contents

@ifnottex

@include include/ifnottex.texinfo

@node Top
@comment  node-name,  next,  previous,  up
@top Alexandria

@insertcopying

@menu
* Hash Tables::
* Data and Control Flow::
* Conses::
* Sequences::
* IO::
* Macro Writing::
* Symbols::
* Arrays::
* Types::
* Numbers::
@end menu

@end ifnottex

@node Hash Tables
@comment  node-name,  next,  previous,  up
@chapter Hash Tables

@include include/macro-alex-2-ensure-gethash.texinfo
@include include/fun-alex-2-copy-hash-table.texinfo
@include include/fun-alex-2-maphash-keys.texinfo
@include include/fun-alex-2-maphash-values.texinfo
@include include/fun-alex-2-hash-table-keys.texinfo
@include include/fun-alex-2-hash-table-values.texinfo
@include include/fun-alex-2-hash-table-alist.texinfo
@include include/fun-alex-2-hash-table-plist.texinfo
@include include/fun-alex-2-alist-hash-table.texinfo
@include include/fun-alex-2-plist-hash-table.texinfo

@node Data and Control Flow
@comment  node-name,  next,  previous,  up
@chapter Data and Control Flow

@include include/macro-alex-2-define-constant.texinfo
@include include/macro-alex-2-destructuring-case.texinfo
@include include/macro-alex-2-ensure-functionf.texinfo
@include include/macro-alex-2-multiple-value-prog2.texinfo
@include include/macro-alex-2-named-lambda.texinfo
@include include/macro-alex-2-nth-value-or.texinfo
@include include/macro-alex-2-if-let.texinfo
@include include/macro-alex-2-when-let.texinfo
@include include/macro-alex-2-when-let-star.texinfo
@include include/macro-alex-2-switch.texinfo
@include include/macro-alex-2-cswitch.texinfo
@include include/macro-alex-2-eswitch.texinfo
@include include/macro-alex-2-whichever.texinfo
@include include/macro-alex-2-xor.texinfo

@include include/fun-alex-2-disjoin.texinfo
@include include/fun-alex-2-conjoin.texinfo
@include include/fun-alex-2-compose.texinfo
@include include/fun-alex-2-ensure-function.texinfo
@include include/fun-alex-2-multiple-value-compose.texinfo
@include include/fun-alex-2-curry.texinfo
@include include/fun-alex-2-rcurry.texinfo

@node Conses
@comment  node-name,  next,  previous,  up
@chapter Conses

@include include/type-alex-2-proper-list.texinfo
@include include/type-alex-2-circular-list.texinfo

@include include/macro-alex-2-appendf.texinfo
@include include/macro-alex-2-nconcf.texinfo
@include include/macro-alex-2-remove-from-plistf.texinfo
@include include/macro-alex-2-delete-from-plistf.texinfo
@include include/macro-alex-2-reversef.texinfo
@include include/macro-alex-2-nreversef.texinfo
@include include/macro-alex-2-unionf.texinfo
@include include/macro-alex-2-nunionf.texinfo

@include include/macro-alex-2-doplist.texinfo

@include include/fun-alex-2-circular-list-p.texinfo
@include include/fun-alex-2-circular-tree-p.texinfo
@include include/fun-alex-2-proper-list-p.texinfo

@include include/fun-alex-2-alist-plist.texinfo
@include include/fun-alex-2-plist-alist.texinfo
@include include/fun-alex-2-circular-list.texinfo
@include include/fun-alex-2-make-circular-list.texinfo
@include include/fun-alex-2-ensure-car.texinfo
@include include/fun-alex-2-ensure-cons.texinfo
@include include/fun-alex-2-ensure-list.texinfo
@include include/fun-alex-2-flatten.texinfo
@include include/fun-alex-2-lastcar.texinfo
@include include/fun-alex-2-setf-lastcar.texinfo
@include include/fun-alex-2-proper-list-length.texinfo
@include include/fun-alex-2-mappend.texinfo
@include include/fun-alex-2-map-product.texinfo
@include include/fun-alex-2-remove-from-plist.texinfo
@include include/fun-alex-2-delete-from-plist.texinfo
@include include/fun-alex-2-delete-from-plist*.texinfo
@include include/fun-alex-2-set-equal.texinfo
@include include/fun-alex-2-setp.texinfo

@node Sequences
@comment  node-name,  next,  previous,  up
@chapter Sequences

@include include/type-alex-2-proper-sequence.texinfo

@include include/macro-alex-2-deletef.texinfo
@include include/macro-alex-2-removef.texinfo

@include include/fun-alex-2-rotate.texinfo
@include include/fun-alex-2-shuffle.texinfo
@include include/fun-alex-2-random-elt.texinfo
@include include/fun-alex-2-emptyp.texinfo
@include include/fun-alex-2-sequence-of-length-p.texinfo
@include include/fun-alex-2-length-equals.texinfo
@include include/fun-alex-2-copy-sequence.texinfo
@include include/fun-alex-2-first-elt.texinfo
@include include/fun-alex-2-setf-first-elt.texinfo
@include include/fun-alex-2-last-elt.texinfo
@include include/fun-alex-2-setf-last-elt.texinfo
@include include/fun-alex-2-starts-with.texinfo
@include include/fun-alex-2-starts-with-subseq.texinfo
@include include/fun-alex-2-ends-with.texinfo
@include include/fun-alex-2-ends-with-subseq.texinfo
@include include/fun-alex-2-map-combinations.texinfo
@include include/fun-alex-2-map-derangements.texinfo
@include include/fun-alex-2-map-permutations.texinfo

@node IO
@comment  node-name,   next,  previous,  up
@chapter IO

@include include/fun-alex-2-read-stream-content-into-string.texinfo
@include include/fun-alex-2-read-file-into-string.texinfo
@include include/fun-alex-2-read-stream-content-into-byte-vector.texinfo
@include include/fun-alex-2-read-file-into-byte-vector.texinfo

@node Macro Writing
@comment  node-name,  next,  previous,  up
@chapter Macro Writing

@include include/macro-alex-2-once-only.texinfo
@include include/macro-alex-2-with-gensyms.texinfo
@include include/macro-alex-2-with-unique-names.texinfo
@include include/fun-alex-2-featurep.texinfo
@include include/fun-alex-2-parse-body.texinfo
@include include/fun-alex-2-parse-ordinary-lambda-list.texinfo

@node Symbols
@comment  node-name,  next,  previous,  up
@chapter Symbols

@include include/fun-alex-2-ensure-symbol.texinfo
@include include/fun-alex-2-format-symbol.texinfo
@include include/fun-alex-2-make-keyword.texinfo
@include include/fun-alex-2-make-gensym.texinfo
@include include/fun-alex-2-make-gensym-list.texinfo
@include include/fun-alex-2-symbolicate.texinfo

@node Arrays
@comment  node-name,  next,  previous,  up
@chapter Arrays

@include include/type-alex-2-array-index.texinfo
@include include/type-alex-2-array-length.texinfo
@include include/fun-alex-2-copy-array.texinfo

@node Types
@comment  node-name,  next,  previous,  up
@chapter Types

@include include/type-alex-2-string-designator.texinfo
@include include/macro-alex-2-coercef.texinfo
@include include/fun-alex-2-of-type.texinfo
@include include/fun-alex-2-type-equals.texinfo

@node Numbers
@comment  node-name,  next,  previous,  up
@chapter Numbers

@include include/macro-alex-2-maxf.texinfo
@include include/macro-alex-2-minf.texinfo

@include include/fun-alex-2-binomial-coefficient.texinfo
@include include/fun-alex-2-count-permutations.texinfo
@include include/fun-alex-2-clamp.texinfo
@include include/fun-alex-2-lerp.texinfo
@include include/fun-alex-2-factorial.texinfo
@include include/fun-alex-2-subfactorial.texinfo
@include include/fun-alex-2-gaussian-random.texinfo
@include include/fun-alex-2-iota.texinfo
@include include/fun-alex-2-map-iota.texinfo
@include include/fun-alex-2-mean.texinfo
@include include/fun-alex-2-median.texinfo
@include include/fun-alex-2-variance.texinfo
@include include/fun-alex-2-standard-deviation.texinfo

@bye
